import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { writeFileSync, symlinkSync } from 'node:fs';
import { join } from 'node:path';
import { scanCommitSecrets } from './commit-secrets.mjs';
import { commitAll, gitFixture } from './test-helpers.mjs';

test('changed-blob scans exclude inherited secrets and retain intermediate, merge, and symlink coverage', t => {
  const {root, git} = gitFixture(t, 'nose-changed-secrets-');
  const token = ['gh','p_'].join('') + randomBytes(18).toString('hex');
  writeFileSync(join(root, 'old.txt'), `token=${token}\n`);
  const initial = commitAll(git);
  assert.equal(scanCommitSecrets(root, initial).status, 'blocked');
  writeFileSync(join(root, 'README.md'), '# Documentation\n');
  const docs = commitAll(git);
  assert.equal(scanCommitSecrets(root, docs).status, 'passed');
  writeFileSync(join(root, 'new.txt'), `token=${token}\n`);
  const added = commitAll(git);
  git('rm', '-q', 'new.txt'); git('commit', '-qm', 'remove fixture');
  assert.equal(scanCommitSecrets(root, added).status, 'blocked');
  assert.equal(scanCommitSecrets(root, git('rev-parse', 'HEAD')).status, 'passed');
  symlinkSync(token, join(root, 'reference'));
  assert.equal(scanCommitSecrets(root, commitAll(git)).status, 'blocked');
  git('switch', '-qc', 'side', docs);
  writeFileSync(join(root, 'merge.txt'), `token=${token}\n`); commitAll(git);
  git('switch', '-qc', 'merge-target', docs);
  writeFileSync(join(root, 'other.txt'), 'safe\n'); commitAll(git);
  git('merge', '--no-ff', '-qm', 'merge fixture', 'side');
  const merged = scanCommitSecrets(root, git('rev-parse', 'HEAD'));
  assert.equal(merged.status, 'blocked');
  assert.ok(merged.findings.some(f => f.file === 'merge.txt'));
  assert.ok(!JSON.stringify(merged).includes(token));
});
