import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { mkdtempSync, writeFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { scanCommitSecrets } from './commit-secrets.mjs';

test('changed-blob scans exclude inherited secrets and retain intermediate, merge, and symlink coverage', t => {
  const root = mkdtempSync(join(tmpdir(), 'nose-changed-secrets-'));
  t.after(() => rmSync(root, {recursive:true, force:true}));
  const git = (...args) => execFileSync('git', args, {cwd:root, encoding:'utf8'}).trim();
  const commit = () => { git('add', '.'); git('commit', '-qm', 'fixture'); return git('rev-parse', 'HEAD'); };
  const token = ['gh','p_'].join('') + randomBytes(18).toString('hex');
  git('init', '-q'); git('config', 'user.name', 'Test'); git('config', 'user.email', 'test@example.invalid');
  writeFileSync(join(root, 'old.txt'), `token=${token}\n`);
  const initial = commit();
  assert.equal(scanCommitSecrets(root, initial).status, 'blocked');
  writeFileSync(join(root, 'README.md'), '# Documentation\n');
  const docs = commit();
  assert.equal(scanCommitSecrets(root, docs).status, 'passed');
  writeFileSync(join(root, 'new.txt'), `token=${token}\n`);
  const added = commit();
  git('rm', '-q', 'new.txt'); git('commit', '-qm', 'remove fixture');
  assert.equal(scanCommitSecrets(root, added).status, 'blocked');
  assert.equal(scanCommitSecrets(root, git('rev-parse', 'HEAD')).status, 'passed');
  symlinkSync(token, join(root, 'reference'));
  assert.equal(scanCommitSecrets(root, commit()).status, 'blocked');
  git('switch', '-qc', 'side', docs);
  writeFileSync(join(root, 'merge.txt'), `token=${token}\n`); commit();
  git('switch', '-qc', 'merge-target', docs);
  writeFileSync(join(root, 'other.txt'), 'safe\n'); commit();
  git('merge', '--no-ff', '-qm', 'merge fixture', 'side');
  const merged = scanCommitSecrets(root, git('rev-parse', 'HEAD'));
  assert.equal(merged.status, 'blocked');
  assert.ok(merged.findings.some(f => f.file === 'merge.txt'));
  assert.ok(!JSON.stringify(merged).includes(token));
});
